### ISSUE TITLE
Bill of Material should allow short hand for namespaces

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/iascable#108]
Currently to specify a particular namespace for a module, a lot of configuration is required.

```yaml
modules:
  - name: gitops-namespace
    alias: tools
    variables:
      - name: name
        value: tools
  - name: gitops-mymodule
    dependencies:
      - id: namespace
        ref: tools
```

We should be able to provide shorthand to reduce the number of elements required. E.g.

```yaml
modules:
  - name: gitops-mymodule
    namespace: tools
    dependencies:
      - id: namespace
        ref: tools
```
