### ISSUE TITLE
pull default value from parent module in a bom

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/iascable#111]
Example:

```
spec:
  modules:
    - name: ocp-login
    - name: openshift-cicd
```

When this generates you get 3 namespaces created (gitops, tools, sealed-secreates), but generated without default values.  In openshift-cicd we have default values, but they're not being applied/propagated.
