### ISSUE TITLE
Maureen would like an easier way to describe dependencies in the BOM 

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/iascable#112]
Currently we have to do this: 

```
spec:
  modules:
    - name: ocp-login
    - name: openshift-cicd
    - name: console-link-job
      dependencies:
        - name: namespace
          ref: tools
    - name: cluster-config
      alias: config
      dependencies:
        - name: namespace
          ref: tools
    - name: namespace
      alias: tools
      variables:
        - name: name
          value: tools
```          

Ideally we could do this: 

```
spec:
  modules:
    - name: ocp-login
    - name: openshift-cicd
    - name: console-link-job
      dependsOn: tools
    - name: cluster-config
      alias: config
      dependsOn: 
        - tools
    - name: namespace
      alias: tools
      variables:
        - name: name
          value: tools
```
