### ISSUE TITLE
generated output for ibm-ocp-vpc does not autowire the kms

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/iascable#140]
When generating either [130](https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/ibmcloud/openshift-fs/130-ibm-fs-management-vpc-openshift.yaml) or [150](https://github.com/cloud-native-toolkit/automation-solutions/blob/main/boms/infrastructure/ibmcloud/openshift-fs/150-ibm-fs-workload-vpc-openshift.yaml) the kms key is not autowired

In the BOM, it looks like this:
```
    - name: ibm-ocp-vpc
      alias: cluster
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
        - name: worker_count
          alias: workload_worker_count
        - name: ocp_version
          value: 4.8
      dependencies:
        - name: subnets
          ref: worker-subnets
        - name: kms_key
          ref: kms_key
```

Which should autowire the kms key based on the contents of it's module.yaml.

Howere, the generated output looks like this:

```
module "cluster" {
  source = "cloud-native-toolkit/ocp-vpc/ibm"
  version = "1.13.2"

  cos_id = module.cos.id
  disable_public_endpoint = var.cluster_disable_public_endpoint
  exists = var.cluster_exists
  flavor = var.cluster_flavor
  force_delete_storage = var.cluster_force_delete_storage
  ibmcloud_api_key = var.ibmcloud_api_key
  kms_enabled = var.cluster_kms_enabled
  kms_id = var.cluster_kms_id
  kms_key_id = var.cluster_kms_key_id
  kms_private_endpoint = var.cluster_kms_private_endpoint
  login = var.cluster_login
  name = var.cluster_name
  name_prefix = var.mgmt_name_prefix
  ocp_entitlement = var.cluster_ocp_entitlement
  ocp_version = var.ocp_version
  region = var.region
  resource_group_name = module.resource_group.name
  sync = module.resource_group.sync
  tags = var.cluster_tags == null ? null : jsondecode(var.cluster_tags)
  vpc_name = module.worker-subnets.vpc_name
  vpc_subnet_count = module.worker-subnets.count
  vpc_subnets = module.worker-subnets.subnets
  worker_count = var.mgmt_worker_count
}
```

Notice all of the kms values are individual variables:
```
  kms_enabled = var.cluster_kms_enabled
  kms_id = var.cluster_kms_id
  kms_key_id = var.cluster_kms_key_id
  kms_private_endpoint = var.cluster_kms_private_endpoint
```

If you try to execute the template, you get these errors:
```

│ Error: Invalid value for module argument
│
│   on main.tf line 141, in module "ibm-transit-gateway":
│  141:   connections = module.ibm-vpc.crn
│
│ The given value is not suitable for child module variable "connections" defined at
│ .terraform/modules/ibm-transit-gateway/variables.tf:24,1-23: list of string required.
╵
-----
╷
│ Error: Missing required argument
│
│   with module.cluster.ibm_container_vpc_cluster.cluster[0],
│   on .terraform/modules/cluster/main.tf line 197, in resource "ibm_container_vpc_cluster" "cluster":
│  197: resource ibm_container_vpc_cluster cluster {
│
│ The argument "kms_config.0.instance_id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   with module.cluster.ibm_container_vpc_cluster.cluster[0],
│   on .terraform/modules/cluster/main.tf line 197, in resource "ibm_container_vpc_cluster" "cluster":
│  197: resource ibm_container_vpc_cluster cluster {
│
│ The argument "kms_config.0.crk_id" is required, but no definition was found.
╵
```

In the [old generated FS Cloud template](https://github.ibm.com/gsi-labs/ibmcloud-reference-architectures/blob/main/130-management-vpc-openshift/terraform/stages.tf#L114), it gets autowired like so:
```
  kms_id = module.kms-key.kms_id
  kms_key_id = module.kms-key.id
```

It looks like the [module.yaml](https://github.com/cloud-native-toolkit/terraform-ibm-kms-key/blob/main/module.yaml) for the `kms-key` module hasn't been updated since early november, so something else has changed.

**Comment by seansund** [comment]
I can't reproduce this with iascable `2.11.3`

With this input (current latest for fs-cloud in automation-solutions@main) 
```
apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 130-ibm-fs-management-vpc-openshift
  labels:
    type: infrastructure
    platform: ibm
    code: 130
  annotations:
    displayName: Management VPC OpenShift
    description: Management VPC and Red Hat OpenShift servers
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
    - name: ibm-resource-group
      alias: at_resource_group
    - name: ibm-kms
      alias: kms
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ""
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: mgmt_resource_group_name
          scope: global
    - name: ibm-iam-service-authorization
      alias: flow-log-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: flow-log-collector
        - name: roles
          value:
            - Writer
      dependencies:
        - name: target_resource_group
          ref:  ibm-resource-group
        - name: target_resource
          ref: cos
    - name: ibm-access-group
    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.10.0.0/18
            - 10.20.0.0/18
            - 10.30.0.0/18
    - name: ibm-flow-logs
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: worker-subnets
      variables:
        - name: _count
          alias: mgmt_worker_subnet_count
          scope: global
          value: 3
        - name: label
          value: worker
        - name: ipv4_cidr_blocks
          value:
            - 10.10.10.0/24
            - 10.20.10.0/24
            - 10.30.10.0/24
        - name: acl_rules
          value:
            - {"name":"allow-vpn-ingress","action":"allow","direction":"inbound","source":"0.0.0.0/0", "destination":"10.0.0.0/8"}
            - {"name":"allow-vpn-egress","action":"allow","direction":"outbound","source":"10.0.0.0/8", "destination":"0.0.0.0/0"}
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-ocp-vpc
      alias: cluster
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
        - name: worker_count
          alias: mgmt_worker_count
        - name: ocp_version
          value: 4.8
      dependencies:
        - name: subnets
          ref: worker-subnets
        - name: kms_key
          ref: kms-key
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.10.20.0/24
            - 10.20.20.0/24
            - 10.30.20.0/24
    - name: ibm-vpc-subnets
      alias: ingress-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.10.30.0/24
            - 10.20.30.0/24
            - 10.30.30.0/24
    - name: ibm-vpc-vpn-gateway
      dependencies:
        - name: subnets
          ref: vpn-subnets
    - name: ibm-resource-group
      alias: cs_resource_group
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-kms-key
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-activity-tracker
      dependencies:
        - name: resource_group
          ref: at_resource_group
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    - name: ibm-vpe-gateway
      alias: vpe-cos
      dependencies:
        - name: resource
          ref: cos
        - name: subnets
          ref: vpe-subnets
        - name: sync
          ref: cluster
    - name: ibm-transit-gateway
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource-group
          ref: cs_resource_group
    - name: ibm-log-analysis
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-cloud-monitoring
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-log-analysis-bind
    - name: ibm-cloud-monitoring-bind
  variables:
    - name: mgmt_resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      alias: mgmt_name_prefix
      required: true
    - name: cs_resource_group_name
    - name: cs_name_prefix
    - name: worker_count
    - name: kms_service
```

I get this in the generated main.tf
```
module "cluster" {
  source = "cloud-native-toolkit/ocp-vpc/ibm"
  version = "1.13.3"

  cos_id = module.cos.id
  disable_public_endpoint = var.cluster_disable_public_endpoint
  exists = var.cluster_exists
  flavor = var.cluster_flavor
  force_delete_storage = var.cluster_force_delete_storage
  ibmcloud_api_key = var.ibmcloud_api_key
  kms_enabled = var.cluster_kms_enabled
  kms_id = module.kms-key.kms_id
  kms_key_id = module.kms-key.id
  kms_private_endpoint = var.cluster_kms_private_endpoint
  login = var.cluster_login
  name = var.cluster_name
  name_prefix = var.mgmt_name_prefix
  ocp_entitlement = var.cluster_ocp_entitlement
  ocp_version = var.ocp_version
  region = var.region
  resource_group_name = module.resource_group.name
  sync = module.resource_group.sync
  tags = var.cluster_tags == null ? null : jsondecode(var.cluster_tags)
  vpc_name = module.worker-subnets.vpc_name
  vpc_subnet_count = module.worker-subnets.count
  vpc_subnets = module.worker-subnets.subnets
  worker_count = var.mgmt_worker_count
}
```
