### ISSUE TITLE
If the git slug includes the protocol (e.g. https) for a module dependency then iascable fails to match it

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/iascable#153]
In the module metadata dependencies are identified by using the git slug, e.g. `github.com/org/repo`. However, if the git slug contains the https protocol, then iascable will fail to find the dependency.

Technically including the protocol in the slug is not correct and a separate fix should be made to prevent that in the metadata but to improve usability iascable should be able to find the match even if the url has `https://` in it

E.g. 
```yaml
versions:
    dependencies:
      - id: gitops-cp4d-operator
        refs:
          - source: https://github.com/cloud-native-toolkit/terraform-gitops-cp4d-operator.git
            version: ">= 1.0.0"
 ```
