### ISSUE TITLE
Tools image doesn't work on macOS

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloud-native-toolkit/iascable#163]
FYI: @triceam @csantanapr @timroster

Related project: https://github.com/cloud-native-toolkit/image-cli-tools

## Problems:

When executing following command inside the tools image I get several problems

```sh
sh apply.sh
```

### Problem 1: I need to redefine already defined variable values

Define in the custom-bom.yaml

```yaml
        - name: gitops_repo_repo
          value: "iascable-gitops"
```

Request for input:

```sh
> Provide a value for 'gitops_repo_repo':
  The short name of the repository (i.e. the part after the org/group name)
> iascable-gitops
```

Maybe related to that issue: https://github.com/cloud-native-toolkit/terraform-ibm-vpc-subnets/issues/66

### Problem 2: The token can't be inserted:

```sh
Provide a value for 'gitops_repo_token':
  The personal access token used to access the repository
> 
```

Workaround: I edit the `variables.yaml.tmp` manually on the local computer and insert the needed value.
Maybe related to the issue: https://github.com/cloud-native-toolkit/terraform-ibm-vpc-subnets/issues/66

```yaml
  - name: gitops_repo_token
    value: ghp_XXXX
```

### Problem 3: Terraform init is not invoked

```sh
There are some problems with the CLI configuration:
╷
│ Error: The specified plugin cache dir /home/devops/.terraform.d/plugin-cache cannot be opened: stat /home/devops/.terraform.d/plugin-cache: no such file or directory
│
╵

As a result of the above problems, Terraform may not behave as intended.


Usage: terraform [global options] init [options]

  Initialize a new or existing Terraform working directory by creating
  initial files, loading any remote state, downloading modules, etc.

  This is the first command that should be run for any new or existing
  Terraform configuration per machine. This sets up all the local data
  necessary to run Terraform that is typically not committed to version
  control.

  This command is always safe to run multiple times. Though subsequent runs
  may give errors, this command will never delete your configuration or
  state. Even so, if you have important information, please back it up prior
  to running this command, just in case.

Options:

  -backend=false          Disable backend or Terraform Cloud initialization for
                          this configuration and use what what was previously
                          initialized instead.

                          aliases: -cloud=false

  -backend-config=path    Configuration to be merged with what is in the
                          configuration file's 'backend' block. This can be
                          either a path to an HCL file with key/value
                          assignments (same format as terraform.tfvars) or a
                          'key=value' format, and can be specified multiple
                          times. The backend type must be in the configuration
                          itself.

  -force-copy             Suppress prompts about copying state data when
                          initializating a new state backend. This is
                          equivalent to providing a "yes" to all confirmation
                          prompts.

  -from-module=SOURCE     Copy the contents of the given module into the target
                          directory before initialization.

  -get=false              Disable downloading modules for this configuration.

  -input=false            Disable interactive prompts. Note that some actions may
                          require interactive prompts and will error if input is
                          disabled.

  -lock=false             Don't hold a state lock during backend migration.
                          This is dangerous if others might concurrently run
                          commands against the same workspace.

  -lock-timeout=0s        Duration to retry a state lock.

  -no-color               If specified, output won't contain any color.

  -plugin-dir             Directory containing plugin binaries. This overrides all
                          default search paths for plugins, and prevents the
                          automatic installation of plugins. This flag can be used
                          multiple times.

  -reconfigure            Reconfigure a backend, ignoring any saved
                          configuration.

  -migrate-state          Reconfigure a backend, and attempt to migrate any
                          existing state.

  -upgrade                Install the latest module and provider versions
                          allowed within configured constraints, overriding the
                          default behavior of selecting exactly the version
                          recorded in the dependency lockfile.

  -lockfile=MODE          Set a dependency lockfile mode.
                          Currently only "readonly" is valid.

  -ignore-remote-version  A rare option used for Terraform Cloud and the remote backend
                          only. Set this to ignore checking that the local and remote
                          Terraform versions use compatible state representations, making
                          an operation proceed even when there is a potential mismatch.
                          See the documentation on configuring Terraform with
                          Terraform Cloud for more information.
There are some problems with the CLI configuration:
╷
│ Error: The specified plugin cache dir /home/devops/.terraform.d/plugin-cache cannot be opened: stat /home/devops/.terraform.d/plugin-cache: no such file or directory
│
╵

As a result of the above problems, Terraform may not behave as intended.


╷
│ Error: Module not installed
│ 
│   on main.tf line 1:
│    1: module "argocd-bootstrap" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 18:
│   18: module "cluster" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 46:
│   46: module "cos" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 58:
│   58: module "gitops_repo" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 79:
│   79: module "ibm-vpc" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 94:
│   94: module "ibm-vpc-gateways" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 104:
│  104: module "ibm-vpc-subnets" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 121:
│  121: module "olm" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 128:
│  128: module "resource_group" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 137:
│  137: module "sealed-secret-cert" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
```

## Workaround doesn't work:

When I execute the apply only on my local computer I get another error: You can find her https://github.com/cloud-native-toolkit/iascable/issues/162

### Step 1: BOM definition

```yaml
apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: BillOfMaterial
metadata:
  name: my-ibm-vpc-roks-argocd
spec:
  modules:
    # Virtual Private Cloud - related
    - name: ibm-vpc
      variables:
      - name: ibm-vpc_name
        value: "tsued-gitops-sample"
    - name: ibm-vpc-subnets
      variables:
      - name: ibm-vpc-subnets_label
        value: "tsued-gitops-sample"
      - name: ibm-vpc-subnets__count
        value: 1
    - name: ibm-vpc-gateways
    # ROKS - related
    - name: ibm-ocp-vpc
      variables:
        - name: cluster_name
          value: "tsued-gitops-sample"
        - name: worker_count
          value: 2
        - name: region
          value: "eu-de" 
    # Install OpenShift GitOps and Bootstrap GitOps (aka. ArgoCD) - related
    - name: argocd-bootstrap
      variables:
        - name: gitops_repo_username
          value: "thomassuedbroecker"
        - name: gitops_repo_org
          value: "thomassuedbroecker"
        - name: gitops_repo_token
        - name: gitops_repo_type
          value: "GIT"
        - name: gitops_repo_host
          value: "github.com"
        - name: gitops_repo_repo
          value: "iascable-gitops"
        - name: gitops_repo_server_name
          value: "tsued-gitops-sample"

```

### Step 2: Install [colima](https://github.com/abiosoft/colima) container engine

On macOS

```sh
brew install docker colima
colima start
```

### Step 3: Build the project based on Bill of Material `BOM` file

```sh
iascable build -i my-vpc-roks-argocd-bom.yaml
```

### Step 4: Start the tools container provided by the `IasCable`

```sh
cd output
sh launch
```

### Step 5: In the running container verify the mapped resources

```sh
~/src $ ls
launch.sh               my-ibm-vpc-roks-argocd
```

### Step 6: Use `output/my-ibm-vpc-roks-argocd/apply.sh` to configure the terraform variables.

```sh
cd my-ibm-vpc-roks-argocd
sh apply.sh
```
