### ISSUE TITLE
Apply failing when setting values for common_tags

### ISSUE THREAD

**Issue by timroster** [cloud-native-toolkit/iascable#216]
When using `iascable` version **2.20.0** (also earlier) and adding a `common_tag` global variable - c.f. https://github.com/terraform-ibm-modules/terraform-ibm-toolkit-ocp-vpc/issues/96 there are problems when applying the configuration.

Example BOM
```yaml
apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: test-ibm-vpc-openshift
  labels:
    type: infrastructure
    platform: ibm
    code: '100'
  annotations:
    displayName: IBM VPC OpenShift
    description: IBM VPC and public Red Hat OpenShift server
spec:
  modules:
    - name: ibm-resource-group
    - name: ibm-vpc
    - name: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      default: true
      alias: cluster_subnets
      variables:
        - name: _count
          value: 1
    - name: ibm-ocp-vpc
      variables:
        - name: name
          value: tor-demo
        - name: worker_count
          value: 4
        - name: flavor
          value: bx2.16x64
        - name: force_delete_storage
          value: true
        - name: ocp_version 
          value: "4.10"
    - name: ibm-log-analysis
    - name: ibm-cloud-monitoring
    - name: ibm-log-analysis-bind
    - name: ibm-cloud-monitoring-bind
    - name: ibm-activity-tracker
  variables:
    - name: name_prefix
      value: tor-swetest
    - name: resource_group_name
      value: timro-rg
    - name: region
      value: ca-tor
    - name: tags
      value: ["owner:timro","taztesting"]
    - name: common_tags
      value: ["foobar"]
```

convert to terraform using: `iascable build -i test-ibm-vpc-openshift.yaml` then change to output folder and run `./launch.sh`

after running `apply.sh` the resultant `variables.yaml`:
```
variables:
  - name: ibmcloud_api_key
    value: REDACTED
  - name: region
    value: ca-tor
  - name: name_prefix
    value: tor-swetest
  - name: resource_group_name
    value: timro-rg
  - name: common_tags
    value:
      - foobar
  - name: cluster_subnets__count
    value: 1
  - name: worker_count
    value: 4
  - name: cluster_flavor
    value: bx2.16x64
```

with `terraform.tfvars` containing:
```
ibmcloud_api_key = "REDACTED"
region = "ca-tor"
name_prefix = "tor-swetest"
resource_group_name = "timro-rg"
common_tags = "- foobar"
cluster_subnets__count = "1"
worker_count = "4"
cluster_flavor = "bx2.16x64"
```

Terraform apply is failing with errors of the form:
```
commands will detect it and remind you to do so if necessary.
module.cluster.data.external.dirs: Reading...
module.cluster.data.external.dirs: Read complete after 0s [id=-]
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on .terraform/modules/cluster_subnets/version.tf line 10, in terraform:
│   10:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
╵
╷
│ Warning: Attribute Deprecated
│ 
│   with module.cos.module.clis.random_string.uuid,
│   on .terraform/modules/cos.clis/main.tf line 15, in resource "random_string" "uuid":
│   15:   number  = false
│ 
│ **NOTE**: This is deprecated, use `numeric` instead.
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: Error in function call
│ 
│   on main.tf line 5, in module "cluster":
│    5:   common_tags = var.common_tags == null ? null : jsondecode(var.common_tags)
│     ├────────────────
│     │ var.common_tags is "- foobar"
│ 
│ Call to function "jsondecode" failed: invalid character ' ' in numeric literal.
╵
╷
│ Error: Error in function call
│ 
│   on main.tf line 36, in module "cluster_subnets":
│   36:   common_tags = var.common_tags == null ? null : jsondecode(var.common_tags)
│     ├────────────────
│     │ var.common_tags is "- foobar"
│ 
│ Call to function "jsondecode" failed: invalid character ' ' in numeric literal.
╵
╷
│ Error: Error in function call
│ 
│   on main.tf line 52, in module "cos":
│   52:   common_tags = var.common_tags == null ? null : jsondecode(var.common_tags)
│     ├────────────────
│     │ var.common_tags is "- foobar"
│ 
│ Call to function "jsondecode" failed: invalid character ' ' in numeric literal.
╵
╷
│ Error: Error in function call
│ 
│   on main.tf line 94, in module "ibm-vpc":
│   94:   common_tags = var.common_tags == null ? null : jsondecode(var.common_tags)
│     ├────────────────
│     │ var.common_tags is "- foobar"
│ 
│ Call to function "jsondecode" failed: invalid character ' ' in numeric literal.
╵
╷
│ Error: Error in function call
│ 
│   on main.tf line 107, in module "ibm-vpc-gateways":
│  107:   common_tags = var.common_tags == null ? null : jsondecode(var.common_tags)
│     ├────────────────
│     │ var.common_tags is "- foobar"
│ 
│ Call to function "jsondecode" failed: invalid character ' ' in numeric literal.
```

It appears that there is missing support in the `apply.sh` script to be working with the tfvars file a json instead of simple key string value pairs at the current time.

**Comment by timroster** [comment]
@balasgit FYI

**Comment by balasgit** [comment]
thanks @timroster - keep me posted after it gets resolved as i will try

**Comment by timroster** [comment]
@seansund when I am using the `launch.sh` and `apply.sh` that comes out from the iascable run I am seeing the `terraform.tfvars` looking different:

```terraform
ibmcloud_api_key = "REDACTED"
region = "ca-tor"
name_prefix = "tor-swetest"
resource_group_name = "timro-rg"
common_tags = "- owner:timro
- ctagtest"
cluster_subnets__count = "1"
worker_count = "4"
cluster_flavor = "bx2.16x64"
```

whereas `variables.yaml` is like your example above:

```yaml
variables:
  - name: ibmcloud_api_key
    value: REDACTED
  - name: region
    value: ca-tor
  - name: name_prefix
    value: tor-swetest
  - name: resource_group_name
    value: timro-rg
  - name: common_tags
    value:
      - owner:timro
      - ctagtest
  - name: cluster_subnets__count
    value: 1
  - name: worker_count
    value: 4
  - name: cluster_flavor
    value: bx2.16x64
```

`launch.sh` is selecting this container image: `quay.io/cloudnativetoolkit/cli-tools:v1.2-v2.2.11` and the container image process is running as `devops`. No errors from the apply script (I just accepted w/o edit the proposed value for `common_images`):

```shell
./apply.sh 
Variables can be provided in a yaml file passed as the first argument

Provide a value for 'ibmcloud_api_key':
  The IBM Cloud api key
> REDACTED
Provide a value for 'region':
  Geographic location of the resource (e.g. us-south, us-east)
> (ca-tor) 
Provide a value for 'name_prefix':
  The prefix name for the service. If not provided it will default to the resource group name
> (tor-swetest) 
Provide a value for 'resource_group_name':
  The name of the resource group
> (timro-rg) 
Provide a value for 'common_tags':
  Common tags that should be added to the instance
> (- owner:timro
- ctagtest) 
Provide a value for 'cluster_subnets__count':
  The number of subnets that should be provisioned
> (1) 
Provide a value for 'worker_count':
  The number of worker nodes that should be provisioned for classic infrastructure
> (4) 
Provide a value for 'cluster_flavor':
  The machine type that will be provisioned for classic infrastructure
> (bx2.16x64) 
There are some problems with the CLI configuration:
╷
│ Error: The specified plugin cache dir /home/devops/.terraform.d/plugin-cache cannot be opened: stat /home/devops/.terraform.d/plugin-cache: no such file or directory
│
╵
...
```
