### ISSUE TITLE
Dependencies of modules should not use latest versions

### ISSUE THREAD

**Issue by nheidloff** [cloud-native-toolkit/iascable#252]
Programming languages like Node.js have lots of dependencies. In order to prevent breakages, usually dependencies are defined ('pinned') with a version number. This means that you don't get latest security updates automatically, but you prevent breakages for production apps.

In boms you can define versions of modules. As a consumer you should expect that these versions stay stable and don't pull in later versions of dependencies than they have been tested with.

For example this is not a good practice:

```
    dependencies:
      - id: namespace
        refs:
          - source: github.com/cloud-native-toolkit/terraform-gitops-namespace.git
            version: '>= 1.0.0'   
```
