### ISSUE TITLE
BUG: Silently defaults to latest module version if invalid version is passed

### ISSUE THREAD

**Issue by daniel-butler-irl** [cloud-native-toolkit/iascable#298]
If you pass an invalid module version it appears to silently replace the version with the latest. I think it should throw an error and at the very least give a warning. 
```YAML
apiVersion: cloudnativetoolkit.dev/v1alpha1
kind: BillOfMaterial
metadata:
  name: test
spec:
  modules:
    - name: ibm-resource-group
      version: not_a_valid_version
```
This BOM successfully builds with not warnings, uses the latest version of `ibm-resource-group`
