### ISSUE TITLE
Feature request: Ability to have common variable names between combination of modules

### ISSUE THREAD

**Issue by mrshah-at-ibm** [cloud-native-toolkit/iascable#63]
Currently we have ability to have global variable names or local to a module. The global variable names are taken directly from the module variable name. It will be good to have variable names shared across a few modules.

Example:

In the following BOM, two modules need `name_prefix` defined as variable `mgmt_name_prefix` whereas the other two as `workload_name_prefix`

```yaml
   - name: ibm-kms-key
      alias: mgmt_kms_key
      variables:
        - name: provision
          value: true
        - name: name_prefix
          alias: mgmt_name_prefix
    - name: ibm-object-storage
      alias: mgmt_cos
      dependencies:
        - name: resource_group
          ref: mgmt_resource_group
      variables:
        - name: name_prefix
          ref: mgmt_name_prefix

   - name: ibm-kms-key
      alias: mgmt_kms_key
      variables:
        - name: provision
          value: true
        - name: name_prefix
          alias: workload_name_prefix
    - name: ibm-object-storage
      alias: mgmt_cos
      dependencies:
        - name: resource_group
          ref: workload_resource_group
      variables:
        - name: name_prefix
          ref: workload_name_prefix

```
