### ISSUE TITLE
Dependency that is a list pulls all module instances, not just the one referenced

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/iascable#72]
Dependency that is a list pulls all module instances, not just the one referenced

In 150 bom, There are 2 vpcs:

```
    - name: ibm-vpc
      alias: management-vpc
      dependencies:
        - name: resource_group
          ref: mgmt_resource_group
      variables:
        - name: provision
          value: false
        - name: name
          required: true
        - name: name_prefix
          alias: mgmt_name_prefix
          scope: global

    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.40.0.0/18
            - 10.50.0.0/18
            - 10.60.0.0/18
}
```

Further down in the vpc, I am referencing *only* the second (non-aliased) instance:
```
    - name: ibm-transit-gateway
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource-group
          ref: cs_resource_group
        - name: connections
          ref: ibm-vpc
```

However, the generated output terraform contains a reference to both ibm-vpc modules, so it appears to be too aggressive when handling arrays/lists:
```

module "ibm-transit-gateway" {
  source = "github.com/cloud-native-toolkit/terraform-ibm-transit-gateway?ref=v0.2.2"

  resource_group_name = module.cs_resource_group.name
  connections = [module.ibm-vpc.crn,module.management-vpc.crn]
  region = var.region
  name = var.ibm-transit-gateway_name
  name_prefix = var.cs_name_prefix
  provision = var.ibm-transit-gateway_provision
}
```
(notice there are 2 `connections` when I only expected 1.
