### ISSUE TITLE
Using example baseline-ocp.yaml give subnet errors

### ISSUE THREAD

**Issue by csantanapr** [cloud-native-toolkit/iascable#95]
Use the following example
```yaml
apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: baseline-ocp
spec:
  modules:
    - name: ibm-vpc-gateways
    - name: ibm-ocp-vpc
      variables:
        - name: flavor
          important: true
    - name: openshift-cicd
```
Run iascable
```
iascable build -i baseline-ocp.yaml
```
Run terraform
```
terraform init
terraform plane
terraform deploy
```
Errors
```
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│
│   on .terraform/modules/ibm-vpc-subnets/version.tf line 10, in terraform:
│   10:   experiments = [module_variable_optional_attrs]
│
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.
│
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.
╵
╷
│ Error: Invalid value for module argument
│
│   on main.tf line 64, in module "ibm-vpc-subnets":
│   64:   acl_rules = var.ibm-vpc-subnets_acl_rules == null ? null : jsondecode(var.ibm-vpc-subnets_acl_rules)
│
│ The given value is not suitable for child module variable "acl_rules" defined at .terraform/modules/ibm-vpc-subnets/variables.tf:59,1-21: list of object required.
```
